global using System.Collections.Immutable;
global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.Extensions.Hosting;
global using Microsoft.Extensions.Localization;
global using Microsoft.Extensions.Logging;
global using Microsoft.Extensions.Options;
global using UnoNativationTest.Models;
global using UnoNativationTest.Presentation;
global using UnoNativationTest.DataContracts;
global using UnoNativationTest.DataContracts.Serialization;
global using UnoNativationTest.Services.Caching;
global using UnoNativationTest.Services.Endpoints;
global using ApplicationExecutionState = Windows.ApplicationModel.Activation.ApplicationExecutionState;
global using CommunityToolkit.Mvvm.ComponentModel;
global using CommunityToolkit.Mvvm.Input;
